import { IAppointment } from './appointment.model';
import { Status } from './status.model';

export let APPOINTMENTS: IAppointment[] = [
  {
    id: 1000,
    petName: 'Fifi',
    date: new Date('2024-05-24'),
    hour: 9,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1001,
    petName: 'Max',
    date: new Date('2024-05-24'),
    hour: 10,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1002,
    petName: 'Bella',
    date: new Date('2024-05-24'),
    hour: 11,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1003,
    petName: 'Charlie',
    date: new Date('2024-05-25'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1004,
    petName: 'Daisy',
    date: new Date('2024-05-25'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1005,
    petName: 'Milo',
    date: new Date('2024-05-26'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1006,
    petName: 'Fifi',
    date: new Date('2024-05-26'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1007,
    petName: 'Max',
    date: new Date('2024-05-27'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1008,
    petName: 'Bella',
    date: new Date('2024-05-27'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1009,
    petName: 'Charlie',
    date: new Date('2024-05-28'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1010,
    petName: 'Daisy',
    date: new Date('2024-05-28'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1011,
    petName: 'Milo',
    date: new Date('2024-05-29'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1012,
    petName: 'Fifi',
    date: new Date('2024-05-29'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1013,
    petName: 'Max',
    date: new Date('2024-05-30'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1014,
    petName: 'Bella',
    date: new Date('2024-05-30'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1015,
    petName: 'Charlie',
    date: new Date('2024-05-31'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1016,
    petName: 'Daisy',
    date: new Date('2024-05-31'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1017,
    petName: 'Milo',
    date: new Date('2024-06-01'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1018,
    petName: 'Fifi',
    date: new Date('2024-06-01'),
    hour: 10,
    doctorName: 'Dr. Smith',
    diagnosis: '',
    status: Status.created,
  },
  {
    id: 1019,
    petName: 'Max',
    date: new Date('2024-06-02'),
    hour: 9,
    doctorName: 'Dr. Johnson',
    diagnosis: '',
    status: Status.created,
  },
];
